eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: subject
words: I,You,He,She,It,They,We
server:
  port: 8015
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought,sold,shouted
server:
  port: 8016
---
spring:
  profiles: article
words: a,the
server:
  port: 8017
---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely,likely,mostly
server:
  port: 8018
---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog,Emmanuel,Samuel
server:
  port: 8019
