eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: subject
words: I,You,He,She,It,They,We

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought,sold,shouted

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely,likely,mostly

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog,Emmanuel,Samuel
